a_file := v_file | o_file ;
o_file := file - v_file ;
v_file := ws , [ a_directive , { ows , a_directive } , ws ] ;
file := ws , [ directive , { ows , directive } , ws ] ;

a_directive := v_directive | o_directive ;
o_directive := directive - v_directive ;
v_directive := a_section | a_instruction ;
directive := section | instruction ;

a_section := v_section | o_section ;
o_section := section - v_section ;
v_section := a_section_start , {  ws , a_directive } , ws , a_section_end ;
section := section_start , {  ws , directive } , ws , section_end ;

a_section_start := v_section_start | o_section_start ;
o_section_start := section_start - v_section_start ;
v_section_start := left_angle_bracket ,  [iws] , a_section_header , [iws], right_angle_bracket ;
section_start := left_angle_bracket ,  [iws] , section_header , [iws], right_angle_bracket ;

a_section_end := v_section_end | o_section_end ;
o_section_end := section_end - v_section_end;
v_section_end := left_angle_bracket , [iws] ,  "/" , [iws] , a_section_type , [iws] , right_angle_bracket ;
section_end := left_angle_bracket , [iws] ,  "/" , [iws] , section_type , [iws] , right_angle_bracket ;

a_section_header := v_section_header | o_section_header;
o_section_header := section_header - v_section_header;
v_section_header := a_section_type, [ iws , {  ac - right_angle_bracket } ] ;
section_header := section_type, [ iws , {  ac - right_angle_bracket } ] ;

a_instruction := v_instruction | o_instruction ;
o_instruction := instruction - v_instruction ;
v_instruction := a_keyword , rest_of_line ;
instruction := keyword , rest_of_line ;

a_section_type := v_section_type | o_section_type ;
o_section_type := section_type - v_section_type;
v_section_type := virtualhost ;
section_type := virtualhost
	| ifdefine
	| directory
	| ifmodule
	| location
	| limitexcept
	| limit
	| filesmatch
	;

a_keyword := v_keyword | o_keyword ;
o_keyword := keyword - v_keyword ;
v_keyword := servername | addmonoapplications ;
keyword :=
    userdir
    | user
    | usecanonicalname
    | typesconfig
    | transferlog
    | traceenable
    | timeout
    | threadsperchild
    | startservers
    | sslsessioncachetimeout
    | sslsessioncache
    | sslrandomseed
    | sslprotocol
    | sslpassphrasedialog
    | ssloptions
    | sslhonorcipherorder
    | sslengine
    | sslcompression
    | sslciphersuite
    | sslcertificatekeyfile
    | sslcertificatefile
    | sethandler
    | setenv
    | servertokens
    | serversignature
    | serverroot
    | servername
    | serverenvironment
    | serveradmin
    | scriptalias
    | require
    | readmename
    | protocols
    | processor
    | pidfile
    | order
    | options
    | mutex
    | multiplexer
    | monosetserveralias
    | monorunxsp
    | monodebug
    | monoautoapplication
    | minsparethreads
    | minspareservers
    | minspareprocessors
    | minprocessors
    | mimemagicfile
    | mcachesize
    | mcacheminobjectsize
    | mcachemaxobjectsize
    | mcachemaxobjectcount
    | maxsparethreads
    | maxspareservers
    | maxrequestworkers
    | maxprocessors
    | maxkeepaliverequests
    | maxconnectionsperchild
    | loglevel
    | logformat
    | loadmodule
    | listen
    | listen
    | ldapsharedcachesize
    | ldapopcachettl
    | ldapopcacheentries
    | ldapcachettl
    | ldapcacheentries
    | languagepriority
    | keepalivetimeout
    | keepalive
    | indexoptions
    | indexignore
    | hostnamelookups
    | headername
    | group
    | forcelanguagepriority
    | fileetag
    | extendedstatus
    | expiretimeout
    | errorlog
    | errordocument
    | enablesendfile
    | enablemmap
    | documentroot
    | directoryindex
    | defaulticon
    | davlockdb
    | customlog
    | contentdigest
    | cacheenable
    | browsermatch
    | allowoverride
    | allow
    | alias
    | addtype
    | addoutputfilter
    | addmonoapplications
    | addlanguage
    | addiconbytype
    | addiconbyencoding
    | addicon
    | addhandler
    | addcharset
    | accessfilename
; 

rest_of_line := rest_of_line_char, { rest_of_line_char } ;
rest_of_line_char := ac - (cr | lf);

(* see "section_type" rule *)
addmonoapplicationsifdefine:=("I"|"i"),("F"|"f"),("D"|"d"),("E"|"e"),("F"|"f"),("I"|"i"),("N"|"n"),("E"|"e");
directory:=("D"|"d"),("I"|"i"),("R"|"r"),("E"|"e"),("C"|"c"),("T"|"t"),("O"|"o"),("R"|"r"),("Y"|"y");
ifmodule:=("I"|"i"),("F"|"f"),("M"|"m"),("O"|"o"),("D"|"d"),("U"|"u"),("L"|"l"),("E"|"e");
location:=("L"|"l"),("O"|"o"),("C"|"c"),("A"|"a"),("T"|"t"),("I"|"i"),("O"|"o"),("N"|"n");
limit:=("L"|"l"),("I"|"i"),("M"|"m"),("I"|"i"),("T"|"t");
limitexcept:=("L"|"l"),("I"|"i"),("M"|"m"),("I"|"i"),("T"|"t"),("E"|"e"),("X"|"x"),("C"|"c"),("E"|"e"),("P"|"p"),("T"|"t");
filesmatch:=("F"|"f"),("I"|"i"),("L"|"l"),("E"|"e"),("S"|"s"),("M"|"m"),("A"|"a"),("T"|"t"),("C"|"c"),("H"|"h");

(* see "keyword" rule *)
userdir:=("U"|"u"),("S"|"s"),("E"|"e"),("R"|"r"),("D"|"d"),("I"|"i"),("R"|"r");
user:=("U"|"u"),("S"|"s"),("E"|"e"),("R"|"r");
usecanonicalname:=("U"|"u"),("S"|"s"),("E"|"e"),("C"|"c"),("A"|"a"),("N"|"n"),("O"|"o"),("N"|"n"),("I"|"i"),("C"|"c"),("A"|"a"),("L"|"l"),("N"|"n"),("A"|"a"),("M"|"m"),("E"|"e");
typesconfig:=("T"|"t"),("Y"|"y"),("P"|"p"),("E"|"e"),("S"|"s"),("C"|"c"),("O"|"o"),("N"|"n"),("F"|"f"),("I"|"i"),("G"|"g");
transferlog:=("T"|"t"),("R"|"r"),("A"|"a"),("N"|"n"),("S"|"s"),("F"|"f"),("E"|"e"),("R"|"r"),("L"|"l"),("O"|"o"),("G"|"g");
traceenable:=("T"|"t"),("R"|"r"),("A"|"a"),("C"|"c"),("E"|"e"),("E"|"e"),("N"|"n"),("A"|"a"),("B"|"b"),("L"|"l"),("E"|"e");
timeout:=("T"|"t"),("I"|"i"),("M"|"m"),("E"|"e"),("O"|"o"),("U"|"u"),("T"|"t");
threadsperchild:=("T"|"t"),("H"|"h"),("R"|"r"),("E"|"e"),("A"|"a"),("D"|"d"),("S"|"s"),("P"|"p"),("E"|"e"),("R"|"r"),("C"|"c"),("H"|"h"),("I"|"i"),("L"|"l"),("D"|"d");
startservers:=("S"|"s"),("T"|"t"),("A"|"a"),("R"|"r"),("T"|"t"),("S"|"s"),("E"|"e"),("R"|"r"),("V"|"v"),("E"|"e"),("R"|"r"),("S"|"s");
sslsessioncachetimeout:=("S"|"s"),("S"|"s"),("L"|"l"),("S"|"s"),("E"|"e"),("S"|"s"),("S"|"s"),("I"|"i"),("O"|"o"),("N"|"n"),("C"|"c"),("A"|"a"),("C"|"c"),("H"|"h"),("E"|"e"),("T"|"t"),("I"|"i"),("M"|"m"),("E"|"e"),("O"|"o"),("U"|"u"),("T"|"t");
sslsessioncache:=("S"|"s"),("S"|"s"),("L"|"l"),("S"|"s"),("E"|"e"),("S"|"s"),("S"|"s"),("I"|"i"),("O"|"o"),("N"|"n"),("C"|"c"),("A"|"a"),("C"|"c"),("H"|"h"),("E"|"e");
sslrandomseed:=("S"|"s"),("S"|"s"),("L"|"l"),("R"|"r"),("A"|"a"),("N"|"n"),("D"|"d"),("O"|"o"),("M"|"m"),("S"|"s"),("E"|"e"),("E"|"e"),("D"|"d");
sslprotocol:=("S"|"s"),("S"|"s"),("L"|"l"),("P"|"p"),("R"|"r"),("O"|"o"),("T"|"t"),("O"|"o"),("C"|"c"),("O"|"o"),("L"|"l");
sslpassphrasedialog:=("S"|"s"),("S"|"s"),("L"|"l"),("P"|"p"),("A"|"a"),("S"|"s"),("S"|"s"),("P"|"p"),("H"|"h"),("R"|"r"),("A"|"a"),("S"|"s"),("E"|"e"),("D"|"d"),("I"|"i"),("A"|"a"),("L"|"l"),("O"|"o"),("G"|"g");
ssloptions:=("S"|"s"),("S"|"s"),("L"|"l"),("O"|"o"),("P"|"p"),("T"|"t"),("I"|"i"),("O"|"o"),("N"|"n"),("S"|"s");
sslhonorcipherorder:=("S"|"s"),("S"|"s"),("L"|"l"),("H"|"h"),("O"|"o"),("N"|"n"),("O"|"o"),("R"|"r"),("C"|"c"),("I"|"i"),("P"|"p"),("H"|"h"),("E"|"e"),("R"|"r"),("O"|"o"),("R"|"r"),("D"|"d"),("E"|"e"),("R"|"r");
sslengine:=("S"|"s"),("S"|"s"),("L"|"l"),("E"|"e"),("N"|"n"),("G"|"g"),("I"|"i"),("N"|"n"),("E"|"e");
sslcompression:=("S"|"s"),("S"|"s"),("L"|"l"),("C"|"c"),("O"|"o"),("M"|"m"),("P"|"p"),("R"|"r"),("E"|"e"),("S"|"s"),("S"|"s"),("I"|"i"),("O"|"o"),("N"|"n");
sslciphersuite:=("S"|"s"),("S"|"s"),("L"|"l"),("C"|"c"),("I"|"i"),("P"|"p"),("H"|"h"),("E"|"e"),("R"|"r"),("S"|"s"),("U"|"u"),("I"|"i"),("T"|"t"),("E"|"e");
sslcertificatekeyfile:=("S"|"s"),("S"|"s"),("L"|"l"),("C"|"c"),("E"|"e"),("R"|"r"),("T"|"t"),("I"|"i"),("F"|"f"),("I"|"i"),("C"|"c"),("A"|"a"),("T"|"t"),("E"|"e"),("K"|"k"),("E"|"e"),("Y"|"y"),("F"|"f"),("I"|"i"),("L"|"l"),("E"|"e");
sslcertificatefile:=("S"|"s"),("S"|"s"),("L"|"l"),("C"|"c"),("E"|"e"),("R"|"r"),("T"|"t"),("I"|"i"),("F"|"f"),("I"|"i"),("C"|"c"),("A"|"a"),("T"|"t"),("E"|"e"),("F"|"f"),("I"|"i"),("L"|"l"),("E"|"e");
sethandler:=("S"|"s"),("E"|"e"),("T"|"t"),("H"|"h"),("A"|"a"),("N"|"n"),("D"|"d"),("L"|"l"),("E"|"e"),("R"|"r");
setenv:=("S"|"s"),("E"|"e"),("T"|"t"),("E"|"e"),("N"|"n"),("V"|"v");
servertokens:=("S"|"s"),("E"|"e"),("R"|"r"),("V"|"v"),("E"|"e"),("R"|"r"),("T"|"t"),("O"|"o"),("K"|"k"),("E"|"e"),("N"|"n"),("S"|"s");
serversignature:=("S"|"s"),("E"|"e"),("R"|"r"),("V"|"v"),("E"|"e"),("R"|"r"),("S"|"s"),("I"|"i"),("G"|"g"),("N"|"n"),("A"|"a"),("T"|"t"),("U"|"u"),("R"|"r"),("E"|"e");
serverroot:=("S"|"s"),("E"|"e"),("R"|"r"),("V"|"v"),("E"|"e"),("R"|"r"),("R"|"r"),("O"|"o"),("O"|"o"),("T"|"t");
servername:=("S"|"s"),("E"|"e"),("R"|"r"),("V"|"v"),("E"|"e"),("R"|"r"),("N"|"n"),("A"|"a"),("M"|"m"),("E"|"e");
serverenvironment:=("S"|"s"),("E"|"e"),("R"|"r"),("V"|"v"),("E"|"e"),("R"|"r"),("E"|"e"),("N"|"n"),("V"|"v"),("I"|"i"),("R"|"r"),("O"|"o"),("N"|"n"),("M"|"m"),("E"|"e"),("N"|"n"),("T"|"t");
serveradmin:=("S"|"s"),("E"|"e"),("R"|"r"),("V"|"v"),("E"|"e"),("R"|"r"),("A"|"a"),("D"|"d"),("M"|"m"),("I"|"i"),("N"|"n");
scriptalias:=("S"|"s"),("C"|"c"),("R"|"r"),("I"|"i"),("P"|"p"),("T"|"t"),("A"|"a"),("L"|"l"),("I"|"i"),("A"|"a"),("S"|"s");
require:=("R"|"r"),("E"|"e"),("Q"|"q"),("U"|"u"),("I"|"i"),("R"|"r"),("E"|"e");
readmename:=("R"|"r"),("E"|"e"),("A"|"a"),("D"|"d"),("M"|"m"),("E"|"e"),("N"|"n"),("A"|"a"),("M"|"m"),("E"|"e");
protocols:=("P"|"p"),("R"|"r"),("O"|"o"),("T"|"t"),("O"|"o"),("C"|"c"),("O"|"o"),("L"|"l"),("S"|"s");
processor:=("P"|"p"),("R"|"r"),("O"|"o"),("C"|"c"),("E"|"e"),("S"|"s"),("S"|"s"),("O"|"o"),("R"|"r");
pidfile:=("P"|"p"),("I"|"i"),("D"|"d"),("F"|"f"),("I"|"i"),("L"|"l"),("E"|"e");
order:=("O"|"o"),("R"|"r"),("D"|"d"),("E"|"e"),("R"|"r");
options:=("O"|"o"),("P"|"p"),("T"|"t"),("I"|"i"),("O"|"o"),("N"|"n"),("S"|"s");
mutex:=("M"|"m"),("U"|"u"),("T"|"t"),("E"|"e"),("X"|"x");
multiplexer:=("M"|"m"),("U"|"u"),("L"|"l"),("T"|"t"),("I"|"i"),("P"|"p"),("L"|"l"),("E"|"e"),("X"|"x"),("E"|"e"),("R"|"r");
monosetserveralias:=("M"|"m"),("O"|"o"),("N"|"n"),("O"|"o"),("S"|"s"),("E"|"e"),("T"|"t"),("S"|"s"),("E"|"e"),("R"|"r"),("V"|"v"),("E"|"e"),("R"|"r"),("A"|"a"),("L"|"l"),("I"|"i"),("A"|"a"),("S"|"s");
monorunxsp:=("M"|"m"),("O"|"o"),("N"|"n"),("O"|"o"),("R"|"r"),("U"|"u"),("N"|"n"),("X"|"x"),("S"|"s"),("P"|"p");
monodebug:=("M"|"m"),("O"|"o"),("N"|"n"),("O"|"o"),("D"|"d"),("E"|"e"),("B"|"b"),("U"|"u"),("G"|"g");
monoautoapplication:=("M"|"m"),("O"|"o"),("N"|"n"),("O"|"o"),("A"|"a"),("U"|"u"),("T"|"t"),("O"|"o"),("A"|"a"),("P"|"p"),("P"|"p"),("L"|"l"),("I"|"i"),("C"|"c"),("A"|"a"),("T"|"t"),("I"|"i"),("O"|"o"),("N"|"n");
minsparethreads:=("M"|"m"),("I"|"i"),("N"|"n"),("S"|"s"),("P"|"p"),("A"|"a"),("R"|"r"),("E"|"e"),("T"|"t"),("H"|"h"),("R"|"r"),("E"|"e"),("A"|"a"),("D"|"d"),("S"|"s");
minspareservers:=("M"|"m"),("I"|"i"),("N"|"n"),("S"|"s"),("P"|"p"),("A"|"a"),("R"|"r"),("E"|"e"),("S"|"s"),("E"|"e"),("R"|"r"),("V"|"v"),("E"|"e"),("R"|"r"),("S"|"s");
minspareprocessors:=("M"|"m"),("I"|"i"),("N"|"n"),("S"|"s"),("P"|"p"),("A"|"a"),("R"|"r"),("E"|"e"),("P"|"p"),("R"|"r"),("O"|"o"),("C"|"c"),("E"|"e"),("S"|"s"),("S"|"s"),("O"|"o"),("R"|"r"),("S"|"s");
minprocessors:=("M"|"m"),("I"|"i"),("N"|"n"),("P"|"p"),("R"|"r"),("O"|"o"),("C"|"c"),("E"|"e"),("S"|"s"),("S"|"s"),("O"|"o"),("R"|"r"),("S"|"s");
mimemagicfile:=("M"|"m"),("I"|"i"),("M"|"m"),("E"|"e"),("M"|"m"),("A"|"a"),("G"|"g"),("I"|"i"),("C"|"c"),("F"|"f"),("I"|"i"),("L"|"l"),("E"|"e");
mcachesize:=("M"|"m"),("C"|"c"),("A"|"a"),("C"|"c"),("H"|"h"),("E"|"e"),("S"|"s"),("I"|"i"),("Z"|"z"),("E"|"e");
mcacheminobjectsize:=("M"|"m"),("C"|"c"),("A"|"a"),("C"|"c"),("H"|"h"),("E"|"e"),("M"|"m"),("I"|"i"),("N"|"n"),("O"|"o"),("B"|"b"),("J"|"j"),("E"|"e"),("C"|"c"),("T"|"t"),("S"|"s"),("I"|"i"),("Z"|"z"),("E"|"e");
mcachemaxobjectsize:=("M"|"m"),("C"|"c"),("A"|"a"),("C"|"c"),("H"|"h"),("E"|"e"),("M"|"m"),("A"|"a"),("X"|"x"),("O"|"o"),("B"|"b"),("J"|"j"),("E"|"e"),("C"|"c"),("T"|"t"),("S"|"s"),("I"|"i"),("Z"|"z"),("E"|"e");
mcachemaxobjectcount:=("M"|"m"),("C"|"c"),("A"|"a"),("C"|"c"),("H"|"h"),("E"|"e"),("M"|"m"),("A"|"a"),("X"|"x"),("O"|"o"),("B"|"b"),("J"|"j"),("E"|"e"),("C"|"c"),("T"|"t"),("C"|"c"),("O"|"o"),("U"|"u"),("N"|"n"),("T"|"t");
maxsparethreads:=("M"|"m"),("A"|"a"),("X"|"x"),("S"|"s"),("P"|"p"),("A"|"a"),("R"|"r"),("E"|"e"),("T"|"t"),("H"|"h"),("R"|"r"),("E"|"e"),("A"|"a"),("D"|"d"),("S"|"s");
maxspareservers:=("M"|"m"),("A"|"a"),("X"|"x"),("S"|"s"),("P"|"p"),("A"|"a"),("R"|"r"),("E"|"e"),("S"|"s"),("E"|"e"),("R"|"r"),("V"|"v"),("E"|"e"),("R"|"r"),("S"|"s");
maxrequestworkers:=("M"|"m"),("A"|"a"),("X"|"x"),("R"|"r"),("E"|"e"),("Q"|"q"),("U"|"u"),("E"|"e"),("S"|"s"),("T"|"t"),("W"|"w"),("O"|"o"),("R"|"r"),("K"|"k"),("E"|"e"),("R"|"r"),("S"|"s");
maxprocessors:=("M"|"m"),("A"|"a"),("X"|"x"),("P"|"p"),("R"|"r"),("O"|"o"),("C"|"c"),("E"|"e"),("S"|"s"),("S"|"s"),("O"|"o"),("R"|"r"),("S"|"s");
maxkeepaliverequests:=("M"|"m"),("A"|"a"),("X"|"x"),("K"|"k"),("E"|"e"),("E"|"e"),("P"|"p"),("A"|"a"),("L"|"l"),("I"|"i"),("V"|"v"),("E"|"e"),("R"|"r"),("E"|"e"),("Q"|"q"),("U"|"u"),("E"|"e"),("S"|"s"),("T"|"t"),("S"|"s");
maxconnectionsperchild:=("M"|"m"),("A"|"a"),("X"|"x"),("C"|"c"),("O"|"o"),("N"|"n"),("N"|"n"),("E"|"e"),("C"|"c"),("T"|"t"),("I"|"i"),("O"|"o"),("N"|"n"),("S"|"s"),("P"|"p"),("E"|"e"),("R"|"r"),("C"|"c"),("H"|"h"),("I"|"i"),("L"|"l"),("D"|"d");
loglevel:=("L"|"l"),("O"|"o"),("G"|"g"),("L"|"l"),("E"|"e"),("V"|"v"),("E"|"e"),("L"|"l");
logformat:=("L"|"l"),("O"|"o"),("G"|"g"),("F"|"f"),("O"|"o"),("R"|"r"),("M"|"m"),("A"|"a"),("T"|"t");
loadmodule:=("L"|"l"),("O"|"o"),("A"|"a"),("D"|"d"),("M"|"m"),("O"|"o"),("D"|"d"),("U"|"u"),("L"|"l"),("E"|"e");
listen:=("L"|"l"),("I"|"i"),("S"|"s"),("T"|"t"),("E"|"e"),("N"|"n");
listen:=("L"|"l"),("I"|"i"),("S"|"s"),("T"|"t"),("E"|"e"),("N"|"n");
ldapsharedcachesize:=("L"|"l"),("D"|"d"),("A"|"a"),("P"|"p"),("S"|"s"),("H"|"h"),("A"|"a"),("R"|"r"),("E"|"e"),("D"|"d"),("C"|"c"),("A"|"a"),("C"|"c"),("H"|"h"),("E"|"e"),("S"|"s"),("I"|"i"),("Z"|"z"),("E"|"e");
ldapopcachettl:=("L"|"l"),("D"|"d"),("A"|"a"),("P"|"p"),("O"|"o"),("P"|"p"),("C"|"c"),("A"|"a"),("C"|"c"),("H"|"h"),("E"|"e"),("T"|"t"),("T"|"t"),("L"|"l");
ldapopcacheentries:=("L"|"l"),("D"|"d"),("A"|"a"),("P"|"p"),("O"|"o"),("P"|"p"),("C"|"c"),("A"|"a"),("C"|"c"),("H"|"h"),("E"|"e"),("E"|"e"),("N"|"n"),("T"|"t"),("R"|"r"),("I"|"i"),("E"|"e"),("S"|"s");
ldapcachettl:=("L"|"l"),("D"|"d"),("A"|"a"),("P"|"p"),("C"|"c"),("A"|"a"),("C"|"c"),("H"|"h"),("E"|"e"),("T"|"t"),("T"|"t"),("L"|"l");
ldapcacheentries:=("L"|"l"),("D"|"d"),("A"|"a"),("P"|"p"),("C"|"c"),("A"|"a"),("C"|"c"),("H"|"h"),("E"|"e"),("E"|"e"),("N"|"n"),("T"|"t"),("R"|"r"),("I"|"i"),("E"|"e"),("S"|"s");
languagepriority:=("L"|"l"),("A"|"a"),("N"|"n"),("G"|"g"),("U"|"u"),("A"|"a"),("G"|"g"),("E"|"e"),("P"|"p"),("R"|"r"),("I"|"i"),("O"|"o"),("R"|"r"),("I"|"i"),("T"|"t"),("Y"|"y");
keepalivetimeout:=("K"|"k"),("E"|"e"),("E"|"e"),("P"|"p"),("A"|"a"),("L"|"l"),("I"|"i"),("V"|"v"),("E"|"e"),("T"|"t"),("I"|"i"),("M"|"m"),("E"|"e"),("O"|"o"),("U"|"u"),("T"|"t");
keepalive:=("K"|"k"),("E"|"e"),("E"|"e"),("P"|"p"),("A"|"a"),("L"|"l"),("I"|"i"),("V"|"v"),("E"|"e");
indexoptions:=("I"|"i"),("N"|"n"),("D"|"d"),("E"|"e"),("X"|"x"),("O"|"o"),("P"|"p"),("T"|"t"),("I"|"i"),("O"|"o"),("N"|"n"),("S"|"s");
indexignore:=("I"|"i"),("N"|"n"),("D"|"d"),("E"|"e"),("X"|"x"),("I"|"i"),("G"|"g"),("N"|"n"),("O"|"o"),("R"|"r"),("E"|"e");
hostnamelookups:=("H"|"h"),("O"|"o"),("S"|"s"),("T"|"t"),("N"|"n"),("A"|"a"),("M"|"m"),("E"|"e"),("L"|"l"),("O"|"o"),("O"|"o"),("K"|"k"),("U"|"u"),("P"|"p"),("S"|"s");
headername:=("H"|"h"),("E"|"e"),("A"|"a"),("D"|"d"),("E"|"e"),("R"|"r"),("N"|"n"),("A"|"a"),("M"|"m"),("E"|"e");
group:=("G"|"g"),("R"|"r"),("O"|"o"),("U"|"u"),("P"|"p");
forcelanguagepriority:=("F"|"f"),("O"|"o"),("R"|"r"),("C"|"c"),("E"|"e"),("L"|"l"),("A"|"a"),("N"|"n"),("G"|"g"),("U"|"u"),("A"|"a"),("G"|"g"),("E"|"e"),("P"|"p"),("R"|"r"),("I"|"i"),("O"|"o"),("R"|"r"),("I"|"i"),("T"|"t"),("Y"|"y");
fileetag:=("F"|"f"),("I"|"i"),("L"|"l"),("E"|"e"),("E"|"e"),("T"|"t"),("A"|"a"),("G"|"g");
extendedstatus:=("E"|"e"),("X"|"x"),("T"|"t"),("E"|"e"),("N"|"n"),("D"|"d"),("E"|"e"),("D"|"d"),("S"|"s"),("T"|"t"),("A"|"a"),("T"|"t"),("U"|"u"),("S"|"s");
expiretimeout:=("E"|"e"),("X"|"x"),("P"|"p"),("I"|"i"),("R"|"r"),("E"|"e"),("T"|"t"),("I"|"i"),("M"|"m"),("E"|"e"),("O"|"o"),("U"|"u"),("T"|"t");
errorlog:=("E"|"e"),("R"|"r"),("R"|"r"),("O"|"o"),("R"|"r"),("L"|"l"),("O"|"o"),("G"|"g");
errordocument:=("E"|"e"),("R"|"r"),("R"|"r"),("O"|"o"),("R"|"r"),("D"|"d"),("O"|"o"),("C"|"c"),("U"|"u"),("M"|"m"),("E"|"e"),("N"|"n"),("T"|"t");
enablesendfile:=("E"|"e"),("N"|"n"),("A"|"a"),("B"|"b"),("L"|"l"),("E"|"e"),("S"|"s"),("E"|"e"),("N"|"n"),("D"|"d"),("F"|"f"),("I"|"i"),("L"|"l"),("E"|"e");
enablemmap:=("E"|"e"),("N"|"n"),("A"|"a"),("B"|"b"),("L"|"l"),("E"|"e"),("M"|"m"),("M"|"m"),("A"|"a"),("P"|"p");
documentroot:=("D"|"d"),("O"|"o"),("C"|"c"),("U"|"u"),("M"|"m"),("E"|"e"),("N"|"n"),("T"|"t"),("R"|"r"),("O"|"o"),("O"|"o"),("T"|"t");
directoryindex:=("D"|"d"),("I"|"i"),("R"|"r"),("E"|"e"),("C"|"c"),("T"|"t"),("O"|"o"),("R"|"r"),("Y"|"y"),("I"|"i"),("N"|"n"),("D"|"d"),("E"|"e"),("X"|"x");
defaulticon:=("D"|"d"),("E"|"e"),("F"|"f"),("A"|"a"),("U"|"u"),("L"|"l"),("T"|"t"),("I"|"i"),("C"|"c"),("O"|"o"),("N"|"n");
davlockdb:=("D"|"d"),("A"|"a"),("V"|"v"),("L"|"l"),("O"|"o"),("C"|"c"),("K"|"k"),("D"|"d"),("B"|"b");
customlog:=("C"|"c"),("U"|"u"),("S"|"s"),("T"|"t"),("O"|"o"),("M"|"m"),("L"|"l"),("O"|"o"),("G"|"g");
contentdigest:=("C"|"c"),("O"|"o"),("N"|"n"),("T"|"t"),("E"|"e"),("N"|"n"),("T"|"t"),("D"|"d"),("I"|"i"),("G"|"g"),("E"|"e"),("S"|"s"),("T"|"t");
cacheenable:=("C"|"c"),("A"|"a"),("C"|"c"),("H"|"h"),("E"|"e"),("E"|"e"),("N"|"n"),("A"|"a"),("B"|"b"),("L"|"l"),("E"|"e");
browsermatch:=("B"|"b"),("R"|"r"),("O"|"o"),("W"|"w"),("S"|"s"),("E"|"e"),("R"|"r"),("M"|"m"),("A"|"a"),("T"|"t"),("C"|"c"),("H"|"h");
allowoverride:=("A"|"a"),("L"|"l"),("L"|"l"),("O"|"o"),("W"|"w"),("O"|"o"),("V"|"v"),("E"|"e"),("R"|"r"),("R"|"r"),("I"|"i"),("D"|"d"),("E"|"e");
allow:=("A"|"a"),("L"|"l"),("L"|"l"),("O"|"o"),("W"|"w");
alias:=("A"|"a"),("L"|"l"),("I"|"i"),("A"|"a"),("S"|"s");
addtype:=("A"|"a"),("D"|"d"),("D"|"d"),("T"|"t"),("Y"|"y"),("P"|"p"),("E"|"e");
addoutputfilter:=("A"|"a"),("D"|"d"),("D"|"d"),("O"|"o"),("U"|"u"),("T"|"t"),("P"|"p"),("U"|"u"),("T"|"t"),("F"|"f"),("I"|"i"),("L"|"l"),("T"|"t"),("E"|"e"),("R"|"r");
addmonoapplications:=("A"|"a"),("D"|"d"),("D"|"d"),("M"|"m"),("O"|"o"),("N"|"n"),("O"|"o"),("A"|"a"),("P"|"p"),("P"|"p"),("L"|"l"),("I"|"i"),("C"|"c"),("A"|"a"),("T"|"t"),("I"|"i"),("O"|"o"),("N"|"n"),("S"|"s");
addlanguage:=("A"|"a"),("D"|"d"),("D"|"d"),("L"|"l"),("A"|"a"),("N"|"n"),("G"|"g"),("U"|"u"),("A"|"a"),("G"|"g"),("E"|"e");
addiconbytype:=("A"|"a"),("D"|"d"),("D"|"d"),("I"|"i"),("C"|"c"),("O"|"o"),("N"|"n"),("B"|"b"),("Y"|"y"),("T"|"t"),("Y"|"y"),("P"|"p"),("E"|"e");
addiconbyencoding:=("A"|"a"),("D"|"d"),("D"|"d"),("I"|"i"),("C"|"c"),("O"|"o"),("N"|"n"),("B"|"b"),("Y"|"y"),("E"|"e"),("N"|"n"),("C"|"c"),("O"|"o"),("D"|"d"),("I"|"i"),("N"|"n"),("G"|"g");
addicon:=("A"|"a"),("D"|"d"),("D"|"d"),("I"|"i"),("C"|"c"),("O"|"o"),("N"|"n");
addhandler:=("A"|"a"),("D"|"d"),("D"|"d"),("H"|"h"),("A"|"a"),("N"|"n"),("D"|"d"),("L"|"l"),("E"|"e"),("R"|"r");
addcharset:=("A"|"a"),("D"|"d"),("D"|"d"),("C"|"c"),("H"|"h"),("A"|"a"),("R"|"r"),("S"|"s"),("E"|"e"),("T"|"t");
accessfilename:=("A"|"a"),("C"|"c"),("C"|"c"),("E"|"e"),("S"|"s"),("S"|"s"),("F"|"f"),("I"|"i"),("L"|"l"),("E"|"e"),("N"|"n"),("A"|"a"),("M"|"m"),("E"|"e");

ws := [ ows ] ; (* white space *)
ows := ows_element , { ows_element } ;
ows_element := iws_element | newline ; (* overline white space *)
iws := iws_element , { iws_element } ; 
iws_element := space_or_tab ;  (* inside of line white space *)

space_or_tab := ( space | tab ) , { space | tab } ;
newline := cr | lf | ( cr , lf ) ;
nonspace := ac - ( space | tab | cr | lf ) ;

string := dquote , { string_fragment | escape_sequence } , dquote ; (* string should keep spaces *)
string_fragment := string_fragment_element , { string_fragment_element } ;
string_fragment_element := ac  - (dquote | backslash);
escape_sequence := backslash , ( dquote | backslash | dot );

letter := ? Terminals.Letter ? ;
letter_or_digit := ? Terminals.LetterOrDigit ? ;
ac := ? Terminals.AnyChar ? ;

left_angle_bracket := "<";
right_angle_bracket := ">";
tab := "\x09" ;
lf := "\x0A" ;
cr := "\x0D" ;
space := "\x20" ;
dquote := "\x22";
(* apostrophe := "\x27"; *)
asterisk := "\x2A" ;
dot := "\x2E" ;
slash := "\x2F" ;
backslash := "\x5C" ;
